name: Deploy on Merge
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if merge commit
        run: |
          if [[ $(git log -1 --format=%s) =~ "Merge pull request" ]]; then
            echo "This is a merge commit"
            # Действия при слиянии
            ssh ${SSH_USER}@${SSH_HOST} "docker stop cutaway-container || true && docker rm cutaway-container || true && docker build -t cutaway-image -f Dockerfile.prod . && docker run -d --name cutaway-container -p 5173:5173 cutaway-image"
          else
            echo "Not a merge commit"
            exit 1
          fi
        env:
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
