name: Deploy on Merge
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            if [[ $(git log -1 --format=%s) =~ "Merge pull request" ]]; then
              echo "This is a merge commit"
              docker stop myapp && docker rm myapp && docker build -t myapp . && docker run -d --name myapp myapp
              docker stop cutaway-container || true && docker rm cutaway-container || true && docker build -t cutaway-image -f Dockerfile.prod . && docker run -d --name cutaway-container -p 5173:5173 cutaway-image
            else
              echo "Not a merge commit, skipping deployment"
              exit 1
            fi