name: Deploy project on Merge into origin/master

on:
  pull_request:
    types: [merged]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Остановка контейнера
            docker stop cutaway-container || true
            docker rm cutaway-container || true
            
            # Клонирование репозитория или обновление кода
            cd ~/cutaway
            git pull
            
            # Сборка Docker образа
            docker build -t cutaway-image -f Dockerfile.prod .
            
            # Запуск Docker контейнера
            docker run -d --name cutaway-container -p 5173:5173 cutaway-image
