name: Deploy on Merge
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/cutaway
            eval `ssh-agent -s`
            ssh-add ~/.ssh/GitHub
            git checkout master
            git pull
            if [[ $(git log -1 --format=%s) =~ "Merge pull request" ]]; then
              echo "This is a merge commit"
              docker stop cutaway-container || true && docker rm cutaway-container || true && docker build -t cutaway-image -f docker/Dockerfile.prod . && docker run -d --restart always --name cutaway-container -p 5173:4173 cutaway-image
            else
              echo "Not a merge commit, skipping deployment"
              exit 1
            fi